# this file generates a csv dataset with columns for each seq number and 5000 rows for 5000 unique lotIDs
# the data will be binary 0 or 1

import pandas as pd
import numpy as np

# set random seed for reproducibility
np.random.seed(42)

df = pd.DataFrame(np.random.randint(0, 2, size=(6000, 800)), columns=[f'{i}_stage_step' for i in range(800)])

# the data for each column should be generated by first choosing the proportion of 1s and 0s and then generating the data accordingly

for i in range(800):
    #choose proportion using a beta distribution
    proportion = np.random.uniform(0, 1)
    df[i] = np.random.choice([0, 1], size=6000, p=[proportion, 1-proportion])

# add fake dependency between columns
# make it such that j causes i if i > j
# make seq_501 = 1 if (seq_100 = 1 and seq_200 = 1) else 0
# make seq_601 = 1 if (seq_400 = 0) else 0
# but add a bit of noise in the data

df['501_stage_step'] = np.where((df['100_stage_step'] == 1) & (df['200_stage_step'] == 1), 1, 0)
df['601_stage_step'] = np.where((df['400_stage_step'] == 0), 1, 0)

# flip 10% of 501_stage_step column
df['501_stage_step'] = df['501_stage_step'].apply(lambda x: 1 - x if np.random.rand() < 0.10 else x)

# flip 4% of 601_stage_step column
df['601_stage_step'] = df['601_stage_step'].apply(lambda x: 1 - x if np.random.rand() < 0.04 else x)

# Now, make 700_stage_step = 1 if (501 = 1 and 601 = 1) else 0
df['700_stage_step'] = np.where((df['501_stage_step'] == 1) & (df['601_stage_step'] == 1), 1, 0)

# flip 2% of 700_stage_step column
df['700_stage_step'] = df['700_stage_step'].apply(lambda x: 1 - x if np.random.rand() < 0.02 else x)

# add a column for lot_id
df['lot_id'] = [f'lot_{i}' for i in range(6000)]

# move lot_id to the first column
df = df[['lot_id'] + [col for col in df.columns if col != 'lot_id']]

print(df.head())

# save the dataframe to a csv file
df.to_csv('fake_data.csv', index=False)